#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON="${PROJECT_ROOT}/.venv/bin/python"
MODEL_PATH="${MODEL_PATH:-${PROJECT_ROOT}/models/Qwen2.5-Coder-7B-Instruct}"
TRAIN_DATA="${TRAIN_DATA:-${PROJECT_ROOT}/data/processed/bird_rl_baseline/reasoning_rl/train.parquet}"
VAL_DATA="${VAL_DATA:-${PROJECT_ROOT}/data/processed/bird_rl_baseline/reasoning_rl/val.parquet}"
OUTPUT_DIR="${OUTPUT_DIR:-${PROJECT_ROOT}/checkpoints/bird_rl_reasoning_grpo_smoke}"
NPROC_PER_NODE="${NPROC_PER_NODE:-2}"
TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-1}"
GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.5}"

export PYTHONPATH="${PROJECT_ROOT}/third_party/BIRD-RL:${PROJECT_ROOT}:${PYTHONPATH:-}"
export SQL_REWARD_DB_DIR="${SQL_REWARD_DB_DIR:-${PROJECT_ROOT}/data/raw/six-gym-sqlite/database}"
export SQL_REWARD_NUM_WORKERS="${SQL_REWARD_NUM_WORKERS:-2}"
export SQL_REWARD_BATCH_SIZE="${SQL_REWARD_BATCH_SIZE:-2}"
export HF_HOME="${HF_HOME:-${PROJECT_ROOT}/.cache/huggingface}"
export HF_DATASETS_CACHE="${HF_DATASETS_CACHE:-${HF_HOME}/datasets}"
export TOKENIZERS_PARALLELISM=false
export VLLM_USE_V1=1

"${PYTHON}" -m verl.trainer.main_ppo \
  algorithm.adv_estimator=grpo \
  algorithm.use_kl_in_reward=false \
  algorithm.rollout_correction.bypass_mode=true \
  data.train_files="${TRAIN_DATA}" \
  data.val_files="${VAL_DATA}" \
  data.train_batch_size=2 \
  data.max_prompt_length=4096 \
  data.max_response_length=1024 \
  data.filter_overlong_prompts=true \
  data.filter_overlong_prompts_workers=1 \
  data.dataloader_num_workers=0 \
  data.truncation=error \
  actor_rollout_ref.model.path="${MODEL_PATH}" \
  actor_rollout_ref.model.use_remove_padding=true \
  actor_rollout_ref.model.enable_gradient_checkpointing=true \
  +actor_rollout_ref.model.override_config.attn_implementation=sdpa \
  actor_rollout_ref.model.lora_rank=32 \
  actor_rollout_ref.model.lora_alpha=32 \
  actor_rollout_ref.model.target_modules=all-linear \
  actor_rollout_ref.actor.optim.lr=1e-6 \
  actor_rollout_ref.actor.ppo_mini_batch_size=2 \
  actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
  actor_rollout_ref.actor.use_dynamic_bsz=true \
  actor_rollout_ref.actor.ppo_max_token_len_per_gpu=6144 \
  actor_rollout_ref.actor.use_kl_loss=true \
  actor_rollout_ref.actor.kl_loss_coef=0.01 \
  actor_rollout_ref.actor.kl_loss_type=low_var_kl \
  actor_rollout_ref.actor.entropy_coeff=0 \
  actor_rollout_ref.actor.fsdp_config.param_offload=true \
  actor_rollout_ref.actor.fsdp_config.optimizer_offload=true \
  actor_rollout_ref.actor.fsdp_config.model_dtype=bfloat16 \
  actor_rollout_ref.actor.fsdp_config.use_torch_compile=false \
  actor_rollout_ref.actor.checkpoint.save_contents='["model","extra"]' \
  +actor_rollout_ref.actor.checkpoint.save_lora_only=true \
  actor_rollout_ref.rollout.name=vllm \
  actor_rollout_ref.rollout.mode=async \
  actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
  actor_rollout_ref.rollout.gpu_memory_utilization="${GPU_MEMORY_UTILIZATION}" \
  actor_rollout_ref.rollout.enforce_eager=true \
  actor_rollout_ref.rollout.free_cache_engine=true \
  actor_rollout_ref.rollout.load_format=safetensors \
  actor_rollout_ref.rollout.layered_summon=true \
  actor_rollout_ref.rollout.n=2 \
  actor_rollout_ref.rollout.max_num_batched_tokens=8192 \
  actor_rollout_ref.rollout.max_model_len=6144 \
  actor_rollout_ref.rollout.max_num_seqs=16 \
  actor_rollout_ref.rollout.multi_turn.enable=false \
  actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
  actor_rollout_ref.ref.log_prob_use_dynamic_bsz=true \
  actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=6144 \
  actor_rollout_ref.ref.fsdp_config.param_offload=true \
  actor_rollout_ref.ref.fsdp_config.model_dtype=bfloat16 \
  reward.custom_reward_function.path="${PROJECT_ROOT}/third_party/BIRD-RL/bird_rl/rewards/critic_reward.py" \
  reward.custom_reward_function.name=compute_score \
  reward.reward_manager.name=naive \
  trainer.project_name=driftsql-rl-baselines \
  trainer.experiment_name=bird-rl-reasoning-grpo-smoke \
  trainer.logger='["console"]' \
  trainer.n_gpus_per_node="${NPROC_PER_NODE}" \
  trainer.nnodes=1 \
  trainer.total_training_steps="${TOTAL_TRAINING_STEPS}" \
  trainer.total_epochs=1 \
  trainer.val_before_train=false \
  trainer.save_freq="${TOTAL_TRAINING_STEPS}" \
  trainer.test_freq=-1 \
  trainer.resume_mode=disable \
  trainer.default_local_dir="${OUTPUT_DIR}" \
  trainer.rollout_data_dir="${OUTPUT_DIR}/rollouts" \
  "$@"
